blocks = {
    "1": {
        id:1,
        name:"dirt_drilled",
        breakable:false,
        miningSpeed:0,
        loot:null,
        empty:true,
        
    },

    "2": {
        id:2,
        name:"dirt",
        breakable:true,
        miningSpeed:400,
        loot:null,
        empty:false,
    },
    "3": {
        id:3,
        name:"grass",
        breakable:true,
        miningSpeed:400,
        loot:null,
        empty:false,
    },
    "4": {
        id:4,
        name:'foundation',
        breakable:false,
        empty:false,
        miningSpeed:0,
        loot:null,
    },
    "5": {
        id:5,
        name:'rock',
        breakable:false,
        empty:false,
        miningSpeed:0,
        loot:null,
        min:50,
        max:1000,
        prob:0.01,
        variation:0.0002

    },
    "6": {

    },
    "7": {

    },
    "8": {

    },
    "9": {
        id:9,
        name:"iron_ore",
        breakable:true,
        miningSpeed:800,
        loot:"iron",
        empty:false,
        min:2,
        max:1000,
        prob:0.06,
        variation:0,
        sellPrice:20,
        variation:-0.0005
    },
    "10": {
        id:10,
        name:"gold_ore",
        breakable:true,
        miningSpeed:600,
        loot:"gold",
        empty:false,
        min:50,
        max:1000,
        prob:0.04,
        variation:0,
        sellPrice:50,
    },
    "11": {
        id:11,
        name:"silver_ore",
        breakable:true,
        miningSpeed:1300,
        loot:"silver",
        empty:false,
        min:30,
        max:1000,
        prob:0.05,
        variation:0,
        sellPrice:35,
    },
    "12": {
        id:12,
        name:"copper_ore",
        breakable:true,
        miningSpeed:800,
        loot:"copper",
        empty:false,
        min:20,
        max:1000,
        prob:0.06,
        variation:0,
        sellPrice:30,
    },
    "13": {
        id:13,
        name:"diamond_ore",
        breakable:true,
        miningSpeed:5000,
        loot:"diamond",
        empty:false,
        min:150,
        max:1000,
        prob:0.01,
        variation:0,
        sellPrice:150,
    },

}
